## format = initials_library_cellLine
base_filename: PP_pgPEN_HeLa
fastq_dir: /fh/fast/berger_a/SR/ngs/illumina/pparrish/200722_D00300_1006_AHFFK7BCX3/Unaligned/Project_pparrish/test_array/
fastq_trimmed_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/trimmed_fastqs/200722_HeLa_screen/test_snakemake/
fastq_fofn: fastqs.fofn
demultiplexed_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/demultiplex/200722_HeLa_screen/test_snakemake/
barcode_ref_file: barcode_ref_file.txt
idemp: /home/pparrish/installs/idemp
## add read trim coords
bowtie_idx_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/bowtie1_indices/
bowtie_idx_ref_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/pgRNA_fastas/
aligned_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/bowtie1_aligned/200722_HeLa_screen/test_snakemake/
pgRNA_counts_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/pgRNA_counts/200722_HeLa_screen/test_snakemake
counter_script_dir: /home/pparrish/paralog_pgRNA_screen/scripts
