## format = initials_library_cellLine
base_filename: AB_pgPEN_LNCaP_FGC

## read coordinates; format = [start, end]
R1_coords: [1, 20]
R2_coords: [2, 21]
R3_coords: [1, 6]

## other variables
n_chunks: 1

## reference/config files
bowtie_idx_dir: /fh/fast/nelson_p/Arnab/CRISPR_screens/ref/pgPEN/bowtie1_indices
bowtie_idx_ref_dir: /fh/fast/nelson_p/Arnab/CRISPR_screens/ref/pgPEN/pgRNA_fastas
fastq_fofn: /home/pparrish/pgPEN_pipeline/config/AB_fastqs.fofn
barcode_ref_file: /home/pparrish/pgPEN_pipeline/config/AB_barcode_ref_file.txt
pgRNA_counts_ref: /fh/fast/nelson_p/Arnab/CRISPR_screens/ref/pgPEN/paralog_pgRNA_annotations.txt

## tools not available from conda
idemp: /home/pparrish/installs/idemp/idemp

## directory paths
fastq_dir: /fh/fast/nelson_p/SR/ngs/illumina/abose/211222_D00300_1397_AHNVJCBCX3/Unaligned
fastq_trimmed_dir: /fh/fast/nelson_p/Arnab/CRISPR_screens/211222_pgPEN_LNCaP_FGC/fastq_trimmed
fastq_demuxed_dir: /fh/fast/nelson_p/Arnab/CRISPR_screens/211222_pgPEN_LNCaP_FGC/fastq_demuxed
sam_dir: /fh/fast/nelson_p/Arnab/CRISPR_screens/211222_pgPEN_LNCaP_FGC/sam
bam_dir: /fh/fast/nelson_p/Arnab/CRISPR_screens/211222_pgPEN_LNCaP_FGC/bam
bam_sorted_dir: /fh/fast/nelson_p/Arnab/CRISPR_screens/211222_pgPEN_LNCaP_FGC/bam_sorted
pgRNA_counts_dir: /fh/fast/nelson_p/Arnab/CRISPR_screens/211222_pgPEN_LNCaP_FGC/pgRNA_counts
