## format = initials_library_cellLine
base_filename: PP_pgPEN_HeLa

## read coordinates; format = [start, end]
## - define read coords for the 2 sequencing strategies
R1_coords: [1, 20]
R2_coords: [2, 21]
R3_coords: [1, 6]

## number of chunks to split each BAM file into for pgRNA counting step
## - add some rule-of-thumb info for n_chunks
n_chunks: 50

## reference files
bowtie_idx_ref_dir: config/pgPEN_fasta/
pgRNA_counts_ref: config/pgPEN_annotations.txt
bowtie_idx_dir: config/pgPEN_index/
## config files
barcode_ref_file: config/barcode_ref_file.txt

## directory paths
fastq_trimmed_dir: results/fastq_trimmed
fastq_demuxed_dir: results/fastq_demuxed
sam_dir: results/sam
bam_dir: results/bam
bam_sorted_dir: results/bam_sorted
pgRNA_counts_dir: results/pgRNA_counts

## package
idemp: config/idemp/idemp
