## format = initials_library_cellLine
base_filename: PP_pgPEN_HeLa

## read coordinates; format = [start, end]
## - define read coords for the 2 sequencing strategies
R1_coords: [1, 20]
R2_coords: [2, 21]
R3_coords: [1, 6]

## number of chunks to split each BAM file into for pgRNA counting step
## - add some rule-of-thumb info for n_chunks
n_chunks: 50

## reference files
bowtie_idx_ref_dir: config/pgPEN_fasta/
pgRNA_counts_ref: config/pgPEN_annotations.txt

## config files
barcode_ref_file: config/barcode_ref_file.txt

## tools not available from conda
## - remove once installing idemp is part of the pipeline
idemp: config/idemp/idemp

## directory paths
## - remove once I confirm it can run without this
# fastq_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/pgPEN_library/200122_PC9_screen/results/fastq
# fastq_trimmed_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/pgPEN_library/200122_PC9_screen/results/fastq_trimmed
# fastq_demuxed_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/pgPEN_library/200122_PC9_screen/results/fastq_demuxed
# sam_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/pgPEN_library/200122_PC9_screen/results/sam
# bam_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/pgPEN_library/200122_PC9_screen/results/bam
# bam_sorted_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/pgPEN_library/200122_PC9_screen/results/bam_sorted
# pgRNA_counts_dir: /fh/fast/berger_a/grp/bergerlab_shared/Projects/paralog_pgRNA/pgPEN_library/200122_PC9_screen/results/pgRNA_counts
